name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - treyMart
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

jobs:
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            # Step 1: Check out the repository
            - uses: actions/checkout@v3
              with:
                  submodules: true
                  lfs: false

            # Step 2: Set up Node.js
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            # Step 3: Clean npm cache and install dependencies
            - name: Install Dependencies
              run: |
                  cd packages/frontend
                  npm cache clean --force
                  rm -rf node_modules package-lock.json
                  npm install

            # Step 4: Lint and fix issues (Optional)
            - name: Lint and Fix
              run: |
                  cd packages/frontend
                  npm run lint -- --fix || true

            # Step 5: Build the project
            - name: Build Project
              run: |
                  cd packages/frontend
                  npm run build

            # Step 6: Deploy to Azure Static Web Apps
            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_FIELD_02C1BBF1E }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  action: 'upload'
                  app_location: '/packages/frontend'
                  api_location: ''
                  output_location: 'dist'

    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_FIELD_02C1BBF1E }}
                  action: 'close'
